### ISSUE TITLE
What can I put in didReceiveMemoryWarning?

### ISSUE THREAD

**Issue by sdbarron** [lamprosg/LazyImage#5]
Where are the images stored?  Is there something I can put in didReceiveMemoryWarning to clean up the memory used?

**Comment by lamprosg** [comment]
Greetings sdbarron !

No you don't need to put anything in didReceiveMemoryWarning.

All downloaded images are considered temporary files and are stored in the temporary directory (tmp folder). The system will periodically purge these files when your app is not running. The main idea is if an image is already downloaded don't make a call again to fetch it, but use the saved one from the storage.

So the files may stick around for some time and then be deleted by the OS. If you use a page, that has this image, multiple times even between launches of the app you will be saving many unnecessary internet calls. The temporary directory is managed very nicely by the OS, if storage is running low or for some reason it needs more of it, the tmp folder is the first to be deleted.

**Comment by sdbarron** [comment]
Wow, great info, thanks!
