### ISSUE TITLE
iOS Deployment Target sets to 10!

### ISSUE THREAD

**Issue by iNoles** [lamprosg/LazyImage#8]
in LazyImage.podspec, it has 
```
 s.ios.deployment_target = '10.0'
```

I am wondering is this is a correct deployment target.

**Comment by lamprosg** [comment]
Greetings iNoles. You mean why not lower?

**Comment by iNoles** [comment]
Yeah, is there is a reason that can't be lower than 10.0?

**Comment by lamprosg** [comment]
No specific reason. It could go down to 8.
I will do that with a new release

**Comment by lamprosg** [comment]
Done
